#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     sonarA,         sensorSONAR)
#pragma config(Sensor, S3,     sonarB,         sensorSONAR)
#pragma config(Sensor, S4,     LIGHT,          sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int threshold = 3
int startingValue;

bool doISeeTape();

bool doISeeTape() {
	int value = SensorValue[LIGHT];
	return abs(startingValue - value) >= threshold;
}

task main()
{
int iDistA = SensorValue[sonarA];
int iDistB = SensorValue[sonarB];
int iDistBetween; //figure out later

while(atan((iDistA-iDistB)/iDistBetween)<(sqrt(2)/2)){
	iDistA = SensorValue[sonarA];
	iDistB = SensorValue[sonarB];

	motor[motorD]=50;
	motor[motorE]=50;
	motor[motorF]=50;
	motor[motorG]=50;
}
	motor[motorD]=0;
	motor[motorE]=0;
	motor[motorF]=0;
	motor[motorG]=0;

	wait1Msec(500);

	motor[motorD]=-50;
	motor[motorG]=-50;
	motor[motorF]=50;
	motor[motorE]=50;

	while (!doISeeTape());

	motor[motorD]=0;
	motor[motorE]=0;
	motor[motorF]=0;
	motor[motorG]=0;
}
