#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


int encoderValue = 0;

void moveFoward() {
	motor[backRight] = -50;
	motor[frontRight] = -50;
	motor[backLeft] = 50;
	motor[frontLeft] = 50;
}

<<<<<<< HEAD
void moveFast() {
	motor[backRight] = -100;
	motor[frontRight] = -100;
	motor[backLeft] = 100;
	motor[frontLeft] = 100;
}

void moveRotate(int value) {
	motor[backRight] = 50 * value;
	motor[frontRight] = 50 * value;
	motor[backLeft] = 50 * value;
	motor[frontLeft] = 50 * value;
=======
void moveRotate(int value) {
	motor[backRight] = -50 * value;
	motor[frontRight] = -50 * value;
	motor[backLeft] = -50 * value;
	motor[frontLeft] = -50 * value;
>>>>>>> 40980a24792a420bcfa280320d60c46268cfc742
}

void stopMoving() {
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[backLeft] = 0;
	motor[frontLeft] = 0;
}

task main()
{
<<<<<<< HEAD
	waitForStart();
	moveForard();
	wait1Msec(1500);
	moveRotate(1);
	wait1Msec(500);
	moveFoward();
	wait1Msec(1000);
=======
  //waitForStart();
	moveFoward();
	wait1Msec(2500);
>>>>>>> 40980a24792a420bcfa280320d60c46268cfc742
	stopMoving();
}
