#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"


int encoderValue = 0;

void moveFoward() {
	motor[motor1] = -50;
	motor[motor4] = -50;
	motor[motor2] = 50;
	motor[motor3] = 50;
}

void moveRotate(int value) {
	motor[motor1] = 50 * value;
	motor[motor4] = 50 * value;
	motor[motor2] = 50 * value;
	motor[motor3] = 50 * value;
}

void stopMoving() {
	motor[motor1] = 0;
	motor[motor4] = 0;
	motor[motor2] = 0;
	motor[motor3] = 0;
}

task main()
{
  waitForStart();
	moveFoward();
	wait1Msec(500);
	moveRotate(1);
	nMotorEncoder[motor4] = 0;

	while (encoderValue < 599) {
		encoderValue = nMotorEncoder[motor4];
	}

	moveFoward();
	wait1Msec(1500);
	moveRotate(-1);
	nMotorEncoder[motor4] = 0;
	encoderValue = 0;

	while (encoderValue < 3300) {
		encoderValue = abs(nMotorEncoder[motor4]);
	}

	moveFoward();
	wait1Msec(3000);
}
