#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     lift,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoder = 0;

void stopMoving() {
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[backLeft] = 0;
	motor[frontLeft] = 0;
}

void RmoveForward(int speed, int rotations) {
	motor[backRight] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	nMotorEncoder[frontRight] = 0;
	while (encoder <= rotations) encoder = nMotorEncoder[frontRight];
	stopMoving();
}


void RmoveRotate(int speed, int rotations) {
	motor[backRight] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	nMotorEncoder[frontRight] = 0;
	while (encoder <= rotations) encoder = nMotorEncoder[frontRight];
	stopMoving();
}

void TmoveForward(int speed, int time) {
	motor[backRight] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	wait1Msec(time);
	stopMoving();
}

void TmoveRotate(int speed, int time) {
	motor[backRight] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	wait1Msec(time);
	stopMoving();
}

void moveLiftUp() {
	motor[lift] = 50;
	wait1Msec(100);
}

void moveLiftDown() {
	motor[lift] = -50;
	wait1Msec(100);
}

task main() {

	// move lift thing up
	moveLiftUp();

	// forward
	RmoveForward(50,10);

	// back
	RmoveForward(-50,10);

	// turn right 45 deg
	RmoveRotate(50,1);

	// forward
	RmoveForward(100,50);

	// turn left 270 deg
	RmoveRotate(-50,3);

	// move forward onto ramp
	RmoveForward(100,10);

	//move lift thing down
	moveLiftDown();





}
