#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    lift1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    lift2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int encoder = 0;

void RmoveFoward(int speed, int rotations) {
	motor[backRight] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	nMotorEncoder[frontRight] = 0;
	while (encoder <= rotations) enconder = nMotorEncoder[frontRight];
	stopMoving();
}

void RmoveRotate(int speed, int rotations) {
	motor[backRight] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	nMotorEncoder[frontRight] = 0;
	while (encoder <= rotations) enconder = nMotorEncoder[frontRight];
	stopMoving();
}

void TmoveFoward(int speed, int time) {
	motor[backRight] = -speed;
	motor[frontRight] = -speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	wait1Msec(time);
	stopMoving();
}

void TmoveRotate(int speed, int time) {
	motor[backRight] = speed;
	motor[frontRight] = speed;
	motor[backLeft] = speed;
	motor[frontLeft] = speed;
	wait1Msec(time);
	stopMoving();
}

void stopMoving() {
	motor[backRight] = 0;
	motor[frontRight] = 0;
	motor[backLeft] = 0;
	motor[frontLeft] = 0;
}

void moveLiftUp() {
	servo[lift1] = 255;
	servo[lift2] = 255;
}

void moveLiftDown() {
	servo[lift1] = 30;
	servo[lift2] = 30;
}

task main() {

	// forward
	RmoveFoward(50,10)

	// back
	RmoveForward(-50,10)

	// turn right 45 deg
	RmoveRotate(50,1)

	// forward
	RmoveForward(100,50)

	// turn left 270 deg
	RmoveRotate(-50,3)

	// move forward onto ramp
	RmoveForward(100,10)







}
