#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorA,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorB,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorD,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

/**
VARS
**/
float speed = 1;
bool pressed_d = false;

void initializeRobot()
{
	waitForStart();
	return;
}

void addSpeed(int add)
{
	speed += add;
}

task main()
{
	initializeRobot();
	while (true) {
		int yval = joystick.joy1_y1;
		int xval = joystick.joy1_x1;

		motor[motorA] = (-yval - xval) / speed;
		motor[motorD] = (-yval - xval) / speed;

		motor[motorB] = (yval - xval) / speed;
		motor[motorC] = (yval - xval) / speed;

		if (!pressed_d) {
			if (joystick.joy1_TopHat == 0 || joystick.joy1_TopHat == 4) {
				pressed_d = true;
				if (joystick.joy1_TopHat == 0)
					addSpeed(0.5);
				else
					addSpeed(-0.5)
			}
		} else if (pressed_d && joystick.joy1_TopHat == -1) {
			pressed_d = false;
		}
	}
}
