#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/**
VARS
**/
float speed = 1;
bool pressed_d = false;



void initializeRobot()
{
	waitForStart();
	return;
}

void addSpeed(int add)
{
	speed += add;
}

task main()
{
	initializeRobot();
	while (true) {

	  int yval = joystick.joy1_y1;
		int xval = joystick.joy1_x1;

		motor[motor1] = (-yval - xval) / speed;
		motor[motor4] = (-yval - xval) / speed;

		motor[motor2] = (yval - xval) / speed;
		motor[motor3] = (yval - xval) / speed;

		if (!pressed_d) {
	  		if (joystick.joy1_TopHat == 0 || joystick.joy1_TopHat == 4) {
				pressed_d = true;
				if (joystick.joy1_TopHat == 0)
					addSpeed(0.5);
				else
					addSpeed(-0.5)
			}
		} else if (pressed_d && joystick.joy1_TopHat == -1) {
			pressed_d = false;
		}

		if(joy1Btn(6)==1) // if button 6 is pressed
		{
			servo[servo1]=255; // bulldozer lifts up
			servo[servo6]=255;
		}
		else									// if not pressed bulldozer is down
		{
			servo[servo1]=0;
			servo[servo6]=0;
		}
	}
}
