#pragma config(Motor,  motorA,          Arm,           tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LeftWheel,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          RightWheel,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void imove(int speed, int ticks) {
	motor[RightWheel] = speed;
	motor[LeftWheel] = speed;
	wait1Msec(ticks);
	motor[RightWheel] = 0;
	motor[LeftWheel] = 0;
}

void move(int speed) {
	motor[RightWheel] = speed;
	motor[LeftWheel] = speed;
}

int RIGHT = -1;
int LEFT = 1;

void iturn(int dir, int speed, int ticks) {
	motor[RightWheel] = speed*dir;
	motor[LeftWheel] = -speed*dir;
	wait1Msec(ticks);
	motor[RightWheel] = 0;
	motor[LeftWheel] = 0;
}

void turn(int dir, int speed) {
	motor[RightWheel] = speed*dir;
	motor[LeftWheel] = -speed*dir;
}

void grasp() {
	motor[Arm] = 50;
	wait1Msec(100);
}

void letgo() {
	motor[Arm] = -50;
	wait1Msec(100);
}

task main() {

	while (true) {
		getJoystickSettings(joystick);

		int yval1 = joystick.joy1_y1;
		int yval2 = joystick.joy2_y1;

		if (abs(yval1) < 10) yval1 = 0;
		if (abs(yval2) < 10) yval2 = 0;

		motor[LeftWheel] = yval1;
		motor[RightWheel] = yval2;


	}

}
